services:
  challenge-api:
    image: redteamsubnet61/rest-bex-challenge:1.0.0
    build:
      context: .
      dockerfile: ./src/bex_tracer/challenge/Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    environment:
      CHALLENGE_API_KEY: ${BEX_CHALLENGE_API_KEY:?"BEX_CHALLENGE_API_KEY is not set in .env"}
      BEX_API_PORT: ${BEX_API_PORT:-10001}
    env_file:
      - path: .env
        required: false
    volumes:
      - ./volumes/configs/rest-bex-challenge:/etc/rest-bex-challenge
      - ./volumes/storage/rest-bex-challenge/logs:/var/log/rest-bex-challenge
    shm_size: 2gb
    tmpfs:
      - /run/exc:mode=1777,size=2g,exec
    mem_limit: 8g
    pids_limit: 4096
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETUID
      - SETGID
    ports:
      - "${BEX_API_PORT:-10001}:${BEX_API_PORT:-10001}"
    tty: true
