ENV_PREFIX = "EXC_CHALLENGE_"
ENV_PREFIX_API = f"{ENV_PREFIX}API_"
ENV_PREFIX_CHALLENGE = f"{ENV_PREFIX}CHALLENGE_"

API_SLUG = "rest-exc-challenge"

__all__ = [
    "ENV_PREFIX",
    "ENV_PREFIX_API",
    "ENV_PREFIX_CHALLENGE",
    "API_SLUG",
]
